version: '3'

services:
  db:
    container_name: jpa-test
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Asia/Seoul
    ports:
      - "13306:3306"
